# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["zaphod"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=20\nCONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=20"]'
      branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
